spring.datasource.url=jdbc:mysql://dasules01_mysql-db:3306/facturafacil
spring.datasource.username=facturafacil
spring.datasource.password=aldosivi123

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true